image: rocker/verse:4.2.3
tasks:
  - command: sudo rstudio-server start --server-user gitpod
  
ports:
  - name: RStudio
    description: The RStudio Web Server
    port: 8787
    onOpen: open-browser
